#!/usr/bin/env python
import os, shutil, sys, tarfile
from tempfile import mkdtemp

from pkg_resources import Requirement
from setuptools.package_index import PackageIndex
# Create an spkg of the Separated Sage notebook for inclusion in Sage.

# Get the version from setup.py
version_line = [f for f in open('setup.py').readlines() if 'version' in f][0]
i = version_line.find("'")
j = version_line.rfind("'")
version = version_line[i+1:j]

# Create the sdist

os.system(os.path.join(os.path.curdir, 'sdist'))

# Create the spkg

path = os.path.join('dist','sagenb-%s'%version)
if os.path.exists(path):
    shutil.rmtree(path)

os.makedirs(path)

file = 'sagenb-%s.tar.gz'%version
print "Extracting %s"%file
t = tarfile.open(os.path.join('dist', file))

t.extractall(path)

os.chdir(path)
os.mkdir('src')
shutil.move('sagenb-%s'%version, 'src/sagenb')

spkg_install_fd = open('spkg-install','w')
spkg_install_fd.write("cd src; ")

shutil.copy(os.path.join(os.path.pardir, os.path.pardir, 'SPKG.txt'),
            os.path.curdir)

print "Fetching the required packages"
pkg_index = PackageIndex()

tmp_dir = mkdtemp()
required_packages = ('pytz>=2009r', 'zope.i18nmessageid>=3.5', 'zope.event>=3.4.1',
                     'ClientForm>=0.2.10', 'mechanize>=0.1.11', 'zope.interface>=3.3.0',
                     'zope.schema>=3.5.4', 'zope.testbrowser>=3.7.0a1')
pkg_locations = []

for pkg in required_packages:
    print "Fetching %s" % pkg
    dist = pkg_index.fetch_distribution(Requirement.parse(pkg), tmp_dir, True, True)
    pkg_locations.append(os.path.abspath(dist.location))

for location in pkg_locations:
    shutil.copy(location, 'src')
    spkg_install_fd.write('easy_install %s; ' % os.path.basename(location))

os.chdir(os.path.pardir)

spkg_install_fd.write('cd sagenb; python setup.py install')
spkg_install_fd.close()
shutil.rmtree(tmp_dir)
os.system('sage -pkg sagenb-%s'%version)

