#!/usr/bin/env python
import os, shutil, sys, tarfile

# Create an spkg of the Separated Sage notebook for inclusion in Sage.

# Get the version from setup.py
version_line = [f for f in open('setup.py').readlines() if 'version' in f][0]
i = version_line.find("'")
j = version_line.rfind("'")
version = version_line[i+1:j]

# Create the sdist

if not os.system('./sdist'):
    print "Error running sdist."
    sys.exit(1)

# Create the spkg

path = os.path.join('sdist','sagenb-%s'%version)
if os.path.exists(path):
    shutil.rmtree(path)

os.makedirs(path)

t = tarfile.open(os.path.join('dist', 'sagenb-%s.tar.gz'%version))
t.extractall('path', 'src')

open(os.path.join(path, 'spkg-install'),'w').write("python setup.py install")

shutil.copy('SPKG.txt', path)

os.system('sage -pkg %s'%path)




